package com.example.healthcare.domain

// Generated by tools/generate_verified_ingredient_groups.py.
// Evidence scope/limitations: data-source/recommendation/verified-food-groups.csv.
internal object GeneratedIngredientGroups {
    val byTemplateId: Map<String, VerifiedIngredientGroups> = mapOf(
        "kfind-breakfast-cook-1" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "설탕 약간", "참깨", "물", "소금 적량"), groups = setOf("GRAIN_UNSPECIFIED", "NUT_SEED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("NUT_SEED"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90730",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-breakfast-cook-2" to VerifiedIngredientGroups(
            ingredients = setOf("백미", "카레가루", "감자", "당근", "양파", "고기"), groups = setOf("REFINED_GRAIN", "ROOT_STARCH", "VEGETABLE", "MEAT_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("MEAT_UNSPECIFIED"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231502",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-breakfast-cook-3" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "곤드레"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://www.kasid.org/common/fileDownload/only/boardFile/eyJpdiI6InhkU1ZiQlBkM28zYVpIakZUMUFaVEE9PSIsInZhbHVlIjoiekpTeWZWekxsYVhrMG5mYkM0dzhEdz09IiwibWFjIjoiODYzNGNhYTU1MGZlYzJiNWM0OTFmYjMwZjM4NWVmOGRkZTIxNTdjYmVjZTFkYjU3YjRhN2M4MzU1ZjZhOWRkMSIsInRhZyI6IiJ9",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-breakfast-dining_out-1" to VerifiedIngredientGroups(
            ingredients = setOf("냉면", "무", "오이", "배", "쇠고기", "달걀"), groups = setOf("EGG", "FRUIT", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("EGG", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90738",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-breakfast-convenience-1" to VerifiedIngredientGroups(
            ingredients = setOf("닭가슴살", "토마토", "피클"), groups = setOf("POULTRY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://m.hollys.co.kr/menu/menuView.do?idx=1016&menuDiv=BAKERY",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-breakfast-convenience-2" to VerifiedIngredientGroups(
            ingredients = setOf("브리오슈 프렌치 토스트", "에그샐러드", "치즈", "햄"), groups = setOf("DAIRY", "EGG", "PROCESSED_MEAT"),
            grainType = "NONE", proteinSources = setOf("DAIRY", "EGG", "PROCESSED_MEAT"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.coffeebeankorea.com/menu/list.asp?category=6&category2=1&page=2",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("PROCESSED_MEAT")
        ),
        "kfind-lunch-cook-2" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "채소", "햄", "고기", "달걀"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE", "PROCESSED_MEAT", "EGG", "MEAT_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG", "MEAT_UNSPECIFIED", "PROCESSED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231562",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("PROCESSED_MEAT")
        ),
        "kfind-lunch-dining_out-1" to VerifiedIngredientGroups(
            ingredients = setOf("면", "콩나물", "양배추", "오이", "당근", "매콤달콤한 소스"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178869",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-dinner-cook-1" to VerifiedIngredientGroups(
            ingredients = setOf("고등어", "무", "물", "고추장", "된장", "마늘", "고춧가루", "생강", "소금"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90770",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-dinner-cook-3" to VerifiedIngredientGroups(
            ingredients = setOf("가래떡", "달걀", "쇠고기", "물", "대파", "마늘", "국간장", "소금", "참기름"), groups = setOf("GRAIN_UNSPECIFIED", "RED_MEAT"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92345",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-dinner-convenience-1" to VerifiedIngredientGroups(
            ingredients = setOf("통밀빵", "크랜베리 치킨", "오이"), groups = setOf("WHOLE_GRAIN", "POULTRY", "VEGETABLE"),
            grainType = "WHOLE_WHEAT", proteinSources = setOf("POULTRY"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://www.tlj.co.kr/product/detail.asp?prod_num=3861",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf("RED_MEAT_PRESENT")
        ),
        "kfind-dinner-convenience-2" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "스파게티면", "치즈"), groups = setOf("DAIRY", "GRAIN_UNSPECIFIED", "RED_MEAT"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("DAIRY", "RED_MEAT"),
            cookingStyle = "UNKNOWN", sourceUrl = "http://pizzaschool.net/menu/치즈오븐스파게티/",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-snack-cook-1" to VerifiedIngredientGroups(
            ingredients = setOf("호박"), groups = setOf("VEGETABLE"),
            grainType = "UNKNOWN", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://www.nics.go.kr/food/kfi/foodMonth/view?fd_se=286&fd_snn=133&menu_tab=0",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-snack-cook-2" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "보리"), groups = setOf("MIXED_GRAIN"),
            grainType = "ROASTED_GRAIN_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "ROASTED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=181200",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-snack-dining_out-1" to VerifiedIngredientGroups(
            ingredients = setOf("멥쌀", "막걸리", "설탕", "더운 물", "소금"), groups = setOf("GRAIN_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90306",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-snack-convenience-1" to VerifiedIngredientGroups(
            ingredients = setOf("에스프레소", "우유"), groups = setOf("DAIRY"),
            grainType = "NONE", proteinSources = setOf("DAIRY"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://paikdabang.com/menu/menu_coffee/",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-004000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "물", "배추", "토란대", "된장", "고추장", "대파", "마늘", "소금", "감자 전분", "쌀밥"), groups = setOf("GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90723",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-005000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "귀리"), groups = setOf("MIXED_GRAIN"),
            grainType = "OAT_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://www.nics.go.kr/bbs/view.do?bbsId=news&bbsSn=944466&m=100000020",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-006000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "기장"), groups = setOf("MIXED_GRAIN"),
            grainType = "MILLET_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0021650",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-007000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "단무지", "달걀", "어묵", "당근", "시금치", "김"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE", "EGG", "PROCESSED_FISH"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178926",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-015000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("도토리묵", "쌀", "김치", "오이", "김", "멸치육수"), groups = setOf("ROOT_STARCH", "GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178046",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-016000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "보리"), groups = setOf("MIXED_GRAIN"),
            grainType = "BARLEY_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0023290",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-017000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "양파", "당근"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178056",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-018000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "물", "콩나물", "시금치", "당근", "양파", "고사리", "도라지", "돼지고기", "식용유", "소금", "달걀"), groups = setOf("EGG", "GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92339",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-021000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "수수"), groups = setOf("MIXED_GRAIN"),
            grainType = "SORGHUM_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0021650",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-022000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "물"), groups = setOf("REFINED_GRAIN"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90724",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-023000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "날치알", "당근", "오이", "단무지", "김"), groups = setOf("GRAIN_UNSPECIFIED", "FISH", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("FISH"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=181465",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-025000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("찹쌀", "밤", "대추", "연잎"), groups = setOf("GRAIN_UNSPECIFIED", "ROOT_STARCH"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "STEAMED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178082",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-026000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("곡물", "채소", "찹쌀", "대추", "밤", "은행", "버섯"), groups = setOf("MIXED_GRAIN", "VEGETABLE", "ROOT_STARCH"),
            grainType = "MIXED_GRAINS", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231596",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-027000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "수수", "조", "팥", "콩"), groups = setOf("MIXED_GRAIN", "LEGUME_SOY"),
            grainType = "MIXED_GRAINS", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "STEAMED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0038100",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-032000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "잡곡"), groups = setOf("MIXED_GRAIN"),
            grainType = "MIXED_GRAINS", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0021650",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-033000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "당면", "채소", "고기"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE", "MEAT_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("MEAT_UNSPECIFIED"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231465",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-038000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "차조"), groups = setOf("MIXED_GRAIN"),
            grainType = "MILLET_MIX", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0055188",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-039000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("찹쌀", "팥", "밤", "대추", "소금 약간"), groups = setOf("GRAIN_UNSPECIFIED", "LEGUME_SOY", "ROOT_STARCH"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92064",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d301-043000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "김", "갑오징어", "무", "물", "소금 약간"), groups = setOf("GRAIN_UNSPECIFIED", "SEAFOOD", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91342",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d101-047000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "콩나물"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90727",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d104-181000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭", "쌀", "물", "마늘", "대파", "소금", "참기름"), groups = setOf("GRAIN_UNSPECIFIED", "POULTRY"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=89925",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d304-183000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("백합", "쌀", "물", "참기름", "소금"), groups = setOf("GRAIN_UNSPECIFIED", "SEAFOOD"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90151",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d304-186000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "물", "소금", "참기름"), groups = setOf("GRAIN_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90735",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d304-187000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("민물고기", "민물새우", "쌀", "국수", "깻잎 약간", "소금 약간", "풋고추", "물", "고추장", "고춧가루", "양파", "마늘", "들깻가루", "참기름"), groups = setOf("FISH", "GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=89701",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d304-190000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("잣", "쌀"), groups = setOf("NUT_SEED", "GRAIN_UNSPECIFIED"),
            grainType = "RICE", proteinSources = setOf("NUT_SEED"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0048228",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d104-191000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("전복", "쌀", "물", "참기름", "소금"), groups = setOf("GRAIN_UNSPECIFIED", "SEAFOOD"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=89933",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d304-192000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "설탕 약간", "참깨", "물", "소금 적량"), groups = setOf("GRAIN_UNSPECIFIED", "NUT_SEED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("NUT_SEED"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90730",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d104-194000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀", "당근", "호박", "양파"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=181470",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d104-195000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("팥", "쌀"), groups = setOf("LEGUME_SOY", "GRAIN_UNSPECIFIED"),
            grainType = "RICE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "BOILED", sourceUrl = "https://encykorea.aks.ac.kr/Article/E0049806",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-141000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "양파", "짜장소스", "국수"), groups = setOf("GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231600",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-146000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("가래떡", "닭고기", "두부", "숙주", "양파", "당면", "달걀", "김", "마늘", "소금", "참기름", "후춧가루", "대파"), groups = setOf("GRAIN_UNSPECIFIED", "LEGUME_SOY", "POULTRY", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("LEGUME_SOY", "POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90742",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-148000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("인스턴트 면", "달걀", "파"), groups = setOf("GRAIN_UNSPECIFIED", "EGG"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178959",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d303-151000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("밀가루", "물", "소금", "건표고버섯", "두부", "숙주", "배추김치", "파", "마늘", "깨소금", "참기름½큰술  달걀", "실고추", "대파", "국간장", "마늘½큰술", "물 적량", "후춧가루·참기름 약간"), groups = setOf("GRAIN_UNSPECIFIED", "LEGUME_SOY", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90393",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d303-157000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("국수", "쇠고기", "고사리", "청포묵", "달걀", "도라지", "애호박", "다시마", "소금 약간", "식용유 적량"), groups = setOf("EGG", "GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG", "RED_MEAT"),
            cookingStyle = "DEEP_FRIED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91000",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-160000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("밀가루", "반죽물", "감자", "애호박", "멸치", "달걀", "물", "마늘", "국간장", "대파", "소금", "들기름"), groups = setOf("FISH", "GRAIN_UNSPECIFIED", "ROOT_STARCH"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90739",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-168000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "양파", "호박", "짜장소스", "밀가루 국수"), groups = setOf("GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179699",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-172000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("면", "돼지고기", "채소", "해물", "닭 또는 돼지 뼈 육수"), groups = setOf("GRAIN_UNSPECIFIED", "RED_MEAT", "VEGETABLE", "SEAFOOD"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("RED_MEAT", "SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179704",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-174000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("밀가루", "반죽물", "애호박", "멸치", "달걀", "쇠고기", "감자", "표고버섯", "통마늘", "대파", "김", "물", "국간장", "소금", "참기름"), groups = setOf("EGG", "GRAIN_UNSPECIFIED", "RED_MEAT", "ROOT_STARCH", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90740",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d103-175000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("콩", "국수"), groups = setOf("LEGUME_SOY", "GRAIN_UNSPECIFIED"),
            grainType = "REFINED_NOODLE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "BOILED", sourceUrl = "https://english.visitkorea.or.kr/svc/thingsToDo/foodTrip/special_view.do?vcontsId=178884",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-199000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠갈비", "우거지", "된장", "물 적량", "소금 약간"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90743",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-200000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "양파", "멸치장국국물", "고춧가루", "마늘", "소금"), groups = setOf("ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91015",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-201000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꽃게", "김치"), groups = setOf("SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179219",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-202000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("곰치"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178129",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-203000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "내장 적량", "무", "물", "대파", "국간장 적량", "소금 적량"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91018",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-205000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("배추김치", "두부", "콩나물", "멸치", "물", "대파", "마늘", "참기름", "소금", "고춧가루"), groups = setOf("LEGUME_SOY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90747",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-207000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("낙지", "박"), groups = setOf("SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=180163",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-210000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("달걀", "양파", "물", "대파", "깨소금", "소금", "마늘"), groups = setOf("EGG", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("EGG"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90749",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-213000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭고기", "숙주", "무", "고사리", "양파", "파", "마늘", "국간장", "홍고추", "고춧가루", "생강", "소금", "후춧가루"), groups = setOf("POULTRY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.foodsafetykorea.go.kr/popup/sensuousmenuView.do?rcp_menu_no=261",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-215000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("소 무릎 연골", "힘줄", "쇠고기 양지", "쇠고기 사태", "파", "마늘", "후추"), groups = setOf("RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178304",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-272000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("동태", "무", "양파", "대파", "물", "마늘", "생강", "고춧가루", "국간장", "소금", "후춧가루"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90752",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-218000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("매생이", "굴", "물", "국간장", "마늘", "참기름 약간"), groups = setOf("SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92104",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-223000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("생미역", "고사리", "도라지", "숙주", "국간장", "후춧가루", "식초", "전분", "물 적량"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92108",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-226000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("북어", "간장", "마늘", "소금", "참기름", "파"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.foodsafetykorea.go.kr/popup/sensuousmenuView.do?rcp_menu_no=289",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-228000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭", "찹쌀", "수삼", "대추", "마늘", "물", "소금 적량", "후춧가루 적량"), groups = setOf("POULTRY"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90757",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-231000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠머리", "사골", "도가니", "우설", "유통", "우족", "사태", "쇠고기", "물 적량", "생강 적량", "대파 적량", "마늘 적량"), groups = setOf("RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90419",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-235000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("생아귀", "콩나물", "무", "미나리", "소금", "물"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91426",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d105-237000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("어묵", "대파", "마늘", "소금"), groups = setOf("PROCESSED_FISH"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.foodsafetykorea.go.kr/popup/sensuousmenuView.do?rcp_menu_no=173",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-239000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("미꾸라지", "토란대", "배추시래기", "고사리", "숙주", "부추", "대파", "풋고추", "물", "된장", "호박잎", "방아잎", "국간장", "소금", "초피가루 약간"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91436",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d305-241000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("오이", "물", "식초", "국간장", "소금 적량", "대파", "붉은 고추"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90431",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-259000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("갈치", "애호박", "붉은 고추", "대파", "마늘", "고춧가루", "소금", "물"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91446",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-260000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지 뼈", "감자", "시래기", "대파", "마른 고추", "들깨", "된장", "마늘", "물 적량", "소금 약간"), groups = setOf("RED_MEAT", "ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90170",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d306-266000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("배추김치", "돼지고기", "두부", "풋고추", "양파", "물", "대파", "마늘", "고춧가루", "식용유", "간장 약간", "소금 약간"), groups = setOf("LEGUME_SOY", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90772",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d306-267000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꽁치 통조림", "김치", "마늘", "무", "파"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178268",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-268000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꽃게", "들깨", "양파", "대파", "풋고추", "마늘", "고추 다진 양념", "된장", "물", "국간장 약간"), groups = setOf("NUT_SEED", "SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("NUT_SEED", "SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90171",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-270000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("낙지", "쇠고기", "느타리버섯", "미나리", "붉은 고추", "장국국물", "국간장", "소금 약간"), groups = setOf("RED_MEAT", "SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT", "SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92627",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-273000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("무", "두부", "쑥갓", "물", "국간장 적량", "소금 적량", "생태", "쇠고기", "붉은고추", "대파"), groups = setOf("FISH", "LEGUME_SOY", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH", "LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90446",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-274000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "배추김치", "두부", "무", "양파", "물", "대파", "고추장", "생강", "마늘", "고춧가루", "소금", "후춧가루"), groups = setOf("LEGUME_SOY", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90773",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-275000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "우렁이", "두부", "애호박", "대파", "물", "된장", "소금 약간"), groups = setOf("LEGUME_SOY", "RED_MEAT", "SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT", "SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90189",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d306-276000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("두부", "버섯", "애호박", "배추"), groups = setOf("LEGUME_SOY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.foodnuri.go.kr/portal/bbs/B0000290/view.do?deleteCd=0&menuNo=300089&nttId=233995&pageIndex=9",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d306-279000000-0002" to VerifiedIngredientGroups(
            ingredients = setOf("만두", "김치", "파", "버섯", "두부", "멸치", "다시마", "쇠고기 양지 육수"), groups = setOf("LEGUME_SOY", "VEGETABLE", "RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231433",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-282000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("느타리버섯", "송이버섯", "싸리버섯", "쇠고기", "미나리", "국간장", "쪽파", "육수"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90450",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-284000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("소시지", "햄", "쇠고기", "베이컨", "치즈"), groups = setOf("PROCESSED_MEAT", "RED_MEAT", "DAIRY"),
            grainType = "NONE", proteinSources = setOf("DAIRY", "PROCESSED_MEAT", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178339",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("PROCESSED_MEAT")
        ),
        "kfind-catalog-d106-289000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "두부", "무", "양파", "실파", "당근", "미나리", "표고버섯", "물", "마늘", "소금", "국간장", "참기름", "후춧가루"), groups = setOf("LEGUME_SOY", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90777",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-293000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("명란", "무", "콩나물", "미나리", "풋고추", "붉은 고추", "대파"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91841",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-294000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("오리", "약재", "통마늘", "대추", "밤"), groups = setOf("POULTRY", "ROOT_STARCH"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179458",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-295000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "무", "당근", "건삼", "양파", "느타리버섯", "쑥갓", "미나리", "오리", "밤", "대추", "대파", "들깨", "양파 적량", "물 적량"), groups = setOf("POULTRY", "ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90430",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-296000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("오징어", "콩나물", "감자", "양파", "쑥갓", "물", "대파", "마늘", "고춧가루", "고추장", "소금"), groups = setOf("ROOT_STARCH", "SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90779",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d106-297000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("청국장", "두부", "김치", "쇠고기"), groups = setOf("LEGUME_SOY", "VEGETABLE", "RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=89555",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-352000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("가자미"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "GRILLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231523",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d308-364000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꿩", "채소", "당면", "간장"), groups = setOf("POULTRY", "VEGETABLE", "GRAIN_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179290",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d308-371000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("더덕", "식초 약간"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=89579",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-376000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("소갈비"), groups = setOf("RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92174",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-379000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("뱅어포"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92676",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-382000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기"), groups = setOf("RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90832",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-383000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("삼치"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90833",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-386000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "당근", "양파", "식용유", "대파"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90835",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-392000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("오리고기", "채소", "부추"), groups = setOf("POULTRY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=180155",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d308-395000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("임연수어"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "GRILLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231570",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d108-399000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("조기", "식용유", "소금"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "GRILLED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92363",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-450000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "양파", "대파", "식용유", "간장", "마늘", "설탕"), groups = setOf("ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90854",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-456000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("배추김치", "대파", "식용유", "마늘", "참기름", "설탕"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90855",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-457000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("낙지", "양배추", "양파", "당근", "쪽파", "붉은 고추", "식용유", "소금 약간"), groups = setOf("SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90857",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d310-459000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("느타리버섯", "양파", "간장", "마늘", "파", "참기름", "콩기름", "소금", "깨소금"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://api.nongsaro.go.kr/sample/rest/recomendDiet/recomendDiet.jsp?cntntsNo=89448&tabNo=5",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("REFERENCE_MAJOR_QUANTITY_UNIT_UNVERIFIED")
        ),
        "kfind-catalog-d310-460000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭모래집", "양파", "고추", "피망", "버섯"), groups = setOf("POULTRY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178480",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-462000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "양파", "당근", "대파", "닭", "물 적량"), groups = setOf("POULTRY", "ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90858",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d310-464000000-0002" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "양배추", "양파", "깻잎", "당근", "풋고추", "식용유", "소금 약간"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90859",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-465000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "양배추", "양파", "깻잎", "당근", "풋고추", "식용유", "소금 약간"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90859",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d310-466000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("두부", "김치"), groups = setOf("LEGUME_SOY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "ASSEMBLED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179834",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-467000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("흰떡", "고기", "숙주", "미나리", "당근", "양파", "건표고버섯", "소금 약간", "설탕 약간", "깨소금 약간", "참기름 약간"), groups = setOf("GRAIN_UNSPECIFIED", "MEAT_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90516",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-468000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀떡", "라면", "어묵", "파", "고추장", "고춧가루", "설탕"), groups = setOf("GRAIN_UNSPECIFIED", "PROCESSED_FISH"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231494",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-469000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("마늘종", "양파", "간장", "식용유", "설탕", "통깨", "소금 약간", "참기름 약간"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92523",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-470000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("두부", "돼지고기", "홍고추", "마늘", "생강", "두반장", "청주", "간장", "굴소스", "치킨파우더", "설탕", "녹말물", "고추기름", "물", "후춧가루 약간"), groups = setOf("LEGUME_SOY", "RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "SIMMERED", sourceUrl = "https://api.nongsaro.go.kr/sample/rest/recomendDiet/recomendDiet.jsp?cntntsNo=89306&tabNo=3",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-472000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("멸치", "설탕", "물엿", "통깨", "식용유", "간장"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90862",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-475000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("염장미역줄기", "양파", "당근", "붉은 고추", "통깨", "마늘", "식용유 적량"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90863",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d110-484000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("애호박", "양파", "홍고추", "마늘", "들기름", "새우젓", "소금 약간", "통깨 약간"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://api.nongsaro.go.kr/sample/rest/recomendDiet/recomendDiet.jsp?cntntsNo=89257&tabNo=2",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d311-506000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("가자미", "무", "물"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90839",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-508000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "당근", "양파", "통깨"), groups = setOf("ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90841",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-509000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("고등어", "무"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "BRAISED", sourceUrl = "https://fsis.go.kr/front/contents/cmsView.do?cate_id=0301&cnts_id=13682&select_list_no=127",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-511000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꽁치", "물", "소금"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90842",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-514000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭", "감자", "고춧가루 양념"), groups = setOf("POULTRY", "ROOT_STARCH"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179264",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-515000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭고기", "감자", "당근", "양파", "고추장", "진간장", "마늘", "물엿", "토마토케찹"), groups = setOf("POULTRY", "ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.foodsafetykorea.go.kr/popup/sensuousmenuView.do?rcp_menu_no=252",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d311-516000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("동태", "무", "대파", "실고추 약간"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90845",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-517000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("두부", "홍고추", "파", "마늘"), groups = setOf("LEGUME_SOY"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "BRAISED", sourceUrl = "https://www.foodsafetykorea.go.kr/popup/sensuousmenuView.do?rcp_menu_no=266",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-02", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-518000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("땅콩", "통깨"), groups = setOf("NUT_SEED"),
            grainType = "NONE", proteinSources = setOf("NUT_SEED"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90847",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-519000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("생멸치", "풋고추", "마늘", "간장", "참기름 약간"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90035",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-520000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("무", "멸치", "쌀뜨물", "국간장", "고춧가루", "파", "마늘 적량"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "SIMMERED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90229",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d111-523000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쇠고기", "병어", "물", "실고추"), groups = setOf("FISH", "RED_MEAT"),
            grainType = "NONE", proteinSources = setOf("FISH", "RED_MEAT"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90511",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d107-304000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("참기름", "통깨", "실고추 약간", "가오리"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91148",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d107-310000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("깻잎"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90880",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d307-311000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꼬막", "물 적량", "소금 약간"), groups = setOf("SEAFOOD"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90894",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d107-312000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("꼬막", "소금 약간"), groups = setOf("SEAFOOD"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92606",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d107-318000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("닭", "밤", "건표고버섯", "당근", "대추", "달걀", "대파", "마늘", "간장", "생강즙"), groups = setOf("POULTRY", "ROOT_STARCH"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90243",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d307-320000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("대구", "콩나물", "미나리"), groups = setOf("FISH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "BRAISED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178299",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d107-324000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("돼지고기", "양파", "당근", "붉은 고추", "물"), groups = setOf("RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("RED_MEAT"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92373",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d307-330000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("북어포", "실파", "실고추 약간"), groups = setOf("FISH"),
            grainType = "NONE", proteinSources = setOf("FISH"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90887",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-407000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("가지", "밀가루", "물", "소금", "식용유 적량"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90522",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-408000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "양파", "붉은 고추", "감자 전분", "소금 적량", "식용유 적량"), groups = setOf("ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90868",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-409000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("고구마", "밀가루", "달걀", "쑥갓", "풋고추", "식용유", "소금 적량"), groups = setOf("EGG", "GRAIN_UNSPECIFIED", "ROOT_STARCH", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90231",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d309-410000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("풋고추", "밀가루", "마늘", "국간장 적량"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90233",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d309-411000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("굴", "달걀", "밀가루", "소금", "식용유 적량"), groups = setOf("EGG", "GRAIN_UNSPECIFIED", "SEAFOOD"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("EGG", "SEAFOOD"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90869",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-412000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("묵은 김치", "바지락", "밀가루", "식용유 적량", "소금 약간"), groups = setOf("SEAFOOD", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90234",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d309-413000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("깻잎", "밀가루", "식용유", "소금 약간", "물 약간"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92184",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d309-415000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("거피녹두", "찹쌀가루", "돼지고기", "숙주", "배추김치", "대파", "붉은 고추", "식용유", "소금 약간"), groups = setOf("LEGUME_SOY", "RED_MEAT", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY", "RED_MEAT"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90877",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-416000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("달걀"), groups = setOf("EGG"),
            grainType = "NONE", proteinSources = setOf("EGG"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178911",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d309-418000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("동태살", "밀가루", "달걀", "식용유", "마늘", "소금", "후춧가루 약간"), groups = setOf("EGG", "FISH"),
            grainType = "NONE", proteinSources = setOf("EGG", "FISH"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90872",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d109-419000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("두부", "콩기름", "소금"), groups = setOf("LEGUME_SOY"),
            grainType = "NONE", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "GRILLED", sourceUrl = "https://api.nongsaro.go.kr/sample/rest/recomendDiet/recomendDiet.jsp?cntntsNo=89432&tabNo=0",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("REFERENCE_MAJOR_QUANTITY_UNIT_UNVERIFIED")
        ),
        "kfind-catalog-d109-422000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("메밀가루", "무", "실파", "물", "파", "마늘", "참기름", "깨소금", "소금", "표고버섯", "식용유"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "PAN_COOKED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91134",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d312-538000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("고구마", "당류 시럽"), groups = setOf("ROOT_STARCH"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "DEEP_FRIED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179919",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("SUGAR_HEAVY_DESSERT")
        ),
        "kfind-catalog-d312-540000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("풋고추", "튀김옷"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "DEEP_FRIED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=231392",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d312-541000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("김", "당면", "양파", "당근", "파"), groups = setOf("GRAIN_UNSPECIFIED", "VEGETABLE"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "DEEP_FRIED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178921",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d302-054000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("멥쌀", "소금", "쑥", "오미자", "물 적량", "거피팥", "설탕", "계핏가루", "참기름 적량"), groups = setOf("GRAIN_UNSPECIFIED", "LEGUME_SOY"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("LEGUME_SOY"),
            cookingStyle = "STEAMED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90925",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d102-057000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("쌀떡", "꿀 또는 설탕 소"), groups = setOf("GRAIN_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=179974",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("SUGAR_HEAVY_DESSERT")
        ),
        "kfind-catalog-d302-129000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("밀가루", "소금", "생강즙", "식용유", "잣가루", "물", "녹말 가루 약간"), groups = setOf("GRAIN_UNSPECIFIED"),
            grainType = "RICE_OR_FLOUR", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "DEEP_FRIED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90668",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d114-601000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("가죽", "깨소금"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "UNHEATED", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=91474",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d314-607000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("골뱅이", "북어", "파", "식초", "고춧가루"), groups = setOf("SEAFOOD", "FISH"),
            grainType = "NONE", proteinSources = setOf("FISH", "SEAFOOD"),
            cookingStyle = "UNHEATED", sourceUrl = "https://english.visitkorea.or.kr/svc/sp/food/ext/special_view.do?menuSn=913&vcontsId=178632",
            evidenceScope = "PUBLIC_DISH_DEFINITION", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d114-609000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("굴", "쪽파", "소금", "참기름", "통깨 약간"), groups = setOf("SEAFOOD"),
            grainType = "NONE", proteinSources = setOf("SEAFOOD"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=92201",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d314-613000000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("소금", "노각", "붉은 고추", "대파"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.nics.go.kr/food/kfi/tfSrch08/view?menuId=PS03520&tfcode=90478",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d114-640020000-0001" to VerifiedIngredientGroups(
            ingredients = setOf("감자", "오이", "당근", "마요네즈", "소금", "후추"), groups = setOf("ROOT_STARCH", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "STEAMED", sourceUrl = "https://api.nongsaro.go.kr/sample/rest/recomendDiet/recomendDiet.jsp?cntntsNo=89455&tabNo=1",
            evidenceScope = "PUBLIC_REFERENCE_RECIPE", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf("REFERENCE_MAJOR_QUANTITY_UNIT_UNVERIFIED")
        ),
        "kfind-catalog-d214-640000000-0002" to VerifiedIngredientGroups(
            ingredients = setOf("그릴드 치킨", "오리엔탈소스"), groups = setOf("POULTRY"),
            grainType = "UNKNOWN", proteinSources = setOf("POULTRY"),
            cookingStyle = "GRILLED", sourceUrl = "https://m.hollys.co.kr/menu/menuView.do?idx=665&menuDiv=BAKERY",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-02", eligible = false,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d202-096000000-0010" to VerifiedIngredientGroups(
            ingredients = setOf("감자 브레드", "그릭소스", "로스트 파프리카", "모짜렐라치즈", "양파", "훈제치킨"), groups = setOf("DAIRY", "POULTRY", "VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("DAIRY", "POULTRY"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://www.coffeebeankorea.com/menu/list.asp?category=6&category2=1&page=2",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d202-083000000-0021" to VerifiedIngredientGroups(
            ingredients = setOf("식물성 텐더", "채소"), groups = setOf("VEGETABLE"),
            grainType = "NONE", proteinSources = setOf("UNKNOWN"),
            cookingStyle = "UNHEATED", sourceUrl = "https://cjnews.cj.net/%EB%9A%9C%EB%A0%88%EC%A5%AC%EB%A5%B4-%ED%99%98%EA%B2%BD%EC%9D%98-%EB%82%A0-%EB%A7%9E%EC%95%84-%EC%BA%A0%ED%8E%98%EC%9D%B8-%EC%97%B4%EA%B3%A0-%EB%8C%80%EC%B2%B4%EC%9C%A1-%EC%8B%A0/",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = true,
            negativeSignals = setOf()
        ),
        "kfind-catalog-d202-083000000-0023" to VerifiedIngredientGroups(
            ingredients = setOf("닭고기"), groups = setOf("POULTRY"),
            grainType = "NONE", proteinSources = setOf("POULTRY"),
            cookingStyle = "UNKNOWN", sourceUrl = "https://web-prd.burgerking.co.kr/burgerking/BKR0347.json",
            evidenceScope = "BRAND_OFFICIAL_MAJOR_INGREDIENTS", verifiedAt = "2026-10-04", eligible = false,
            negativeSignals = setOf()
        ),
    )
}
