"""Generate only reviewed major-group evidence, without altering nutrition/Room/292 identities."""
from pathlib import Path
import csv
import json

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data-source/recommendation/verified-food-groups.csv'
TARGET = ROOT / 'app/src/main/java/com/example/healthcare/domain/GeneratedIngredientGroups.kt'

def read(path):
    with path.open(encoding='utf-8-sig', newline='') as handle:
        return list(csv.DictReader(handle))

def generate():
    templates = {row['id']: row for row in read(ROOT / 'app/src/main/assets/fooddata/meal_templates.csv')}
    rows = read(DATA)
    assert len(templates) == 292
    assert len(rows) == len({row['stableTemplateId'] for row in rows})
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    tokens = lambda value: 'setOf(' + ', '.join(quote(token) for token in value.split('|') if token) + ')'
    lines = [
        'package com.example.healthcare.domain', '',
        '// Generated by tools/generate_verified_ingredient_groups.py.',
        '// Evidence scope/limitations: data-source/recommendation/verified-food-groups.csv.',
        'internal object GeneratedIngredientGroups {',
        '    val byTemplateId: Map<String, VerifiedIngredientGroups> = mapOf('
    ]
    for row in rows:
        assert templates[row['stableTemplateId']]['name'] == row['menuName'], row['stableTemplateId']
        assert row['sourceUrl'].startswith(('https://','http://')) and row['ingredients'] and row['foodGroups']
        assert row['sourceUrl'].startswith('https://') or row['slowStyleEligible']=='false'
        assert row['slowStyleEligible'] in ('true', 'false')
        lines += [
            f"        {quote(row['stableTemplateId'])} to VerifiedIngredientGroups(",
            f"            ingredients = {tokens(row['ingredients'])}, groups = {tokens(row['foodGroups'])},",
            f"            grainType = {quote(row['grainType'])}, proteinSources = {tokens(row['proteinSources'])},",
            f"            cookingStyle = {quote(row['cookingStyle'])}, sourceUrl = {quote(row['sourceUrl'])},",
            f"            evidenceScope = {quote(row['evidenceScope'])}, verifiedAt = {quote(row['verifiedAt'])}, eligible = {row['slowStyleEligible']},",
            f"            negativeSignals = {tokens(row.get('negativeSignals', ''))}",
            '        ),'
        ]
    lines += ['    )', '}', '']
    TARGET.write_text('\n'.join(lines), encoding='utf-8')
    print(f'{len(rows)} reviewed major-group entries; 292 template identities unchanged')

if __name__ == '__main__':
    generate()
