param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$AllowIncomplete
)

$ErrorActionPreference = 'Stop'
$catalogPath = Join-Path $ProjectRoot 'app/src/main/assets/fooddata/meal_templates.csv'
$drawablePath = Join-Path $ProjectRoot 'app/src/main/res/drawable-nodpi'
$outputPath = Join-Path $ProjectRoot 'app/src/main/java/com/example/healthcare/ui/GeneratedRecommendationImages.kt'

$catalogRows = @(Import-Csv -LiteralPath $catalogPath)
$mappedRows = foreach ($row in $catalogRows) {
    $resourceName = 'rec_' + ($row.id.ToLowerInvariant() -replace '[^a-z0-9_]', '_')
    $assetPath = Join-Path $drawablePath "$resourceName.jpg"
    if (Test-Path -LiteralPath $assetPath) {
        [pscustomobject]@{ id = $row.id; resourceName = $resourceName }
    } elseif (-not $AllowIncomplete) {
        throw "Missing recommendation image: $($row.id) / $($row.name)"
    }
}

if (-not $AllowIncomplete -and $mappedRows.Count -ne $catalogRows.Count) {
    throw "Recommendation image map is incomplete: $($mappedRows.Count)/$($catalogRows.Count)"
}

$entries = $mappedRows | ForEach-Object {
    '        "' + $_.id + '" to R.drawable.' + $_.resourceName + ','
}
$content = @(
    'package com.example.healthcare.ui'
    ''
    'import com.example.healthcare.R'
    ''
    '/** Generated by tools/generate_recommendation_image_map.ps1. Do not edit manually. */'
    'internal object GeneratedRecommendationImages {'
    '    val templateImages: Map<String, Int> = mapOf('
    $entries
    '    )'
    '}'
) -join [Environment]::NewLine

[System.IO.File]::WriteAllText($outputPath, $content + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $($mappedRows.Count)/$($catalogRows.Count) catalog image mappings: $outputPath"
