create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  version_name text not null,
  version_code integer not null check (version_code > 0),
  platform text not null check (platform in ('android')),
  apk_url text not null check (apk_url ~ '^https://github[.]com/.+/releases/download/.+[.]apk$'),
  file_name text not null check (file_name ~ '[.]apk$'),
  file_size_bytes bigint not null check (file_size_bytes > 0),
  sha256 text not null check (sha256 ~ '^[A-Fa-f0-9]{64}$'),
  release_notes text[] not null default '{}',
  released_at timestamptz not null,
  is_latest boolean not null default false,
  created_at timestamptz not null default now(),
  minimum_android_version text,
  status text not null default 'published' check (status in ('draft', 'published', 'archived'))
);

create unique index if not exists app_releases_platform_version_key
  on public.app_releases (platform, version_code);

create unique index if not exists app_releases_one_latest_per_platform
  on public.app_releases (platform)
  where is_latest = true;

alter table public.app_releases enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'app_releases'
      and policyname = 'Public can read published app releases'
  ) then
    create policy "Public can read published app releases"
      on public.app_releases
      for select
      to anon, authenticated
      using (status = 'published');
  end if;
end
$$;

update public.app_releases
set is_latest = false
where platform = 'android'
  and is_latest = true;

insert into public.app_releases (
  version_name,
  version_code,
  platform,
  apk_url,
  file_name,
  file_size_bytes,
  sha256,
  release_notes,
  released_at,
  is_latest,
  minimum_android_version,
  status
)
values (
  '1.0.2',
  3,
  'android',
  'https://github.com/chlwlgns99970-cmyk/Healthcare/releases/download/v1.0.2/today-mwo-meokji-v1.0.2.apk',
  'today-mwo-meokji-v1.0.2.apk',
  127866676,
  '908EBE76DB874C473525FFB2D0DF79535737FB2AA1DC877F6EDE3BF993070BA5',
  array[
    '메뉴 추천 및 이미지 개선',
    '프랜차이즈 음식 검색 확대',
    '알레르기 정보 표시 개선',
    '운동 추천 및 기록 기능 개선',
    '기존 사용자 업데이트 호환성 개선'
  ],
  '2026-09-27T13:04:54Z'::timestamptz,
  true,
  null,
  'published'
)
on conflict (platform, version_code)
do update set
  version_name = excluded.version_name,
  apk_url = excluded.apk_url,
  file_name = excluded.file_name,
  file_size_bytes = excluded.file_size_bytes,
  sha256 = excluded.sha256,
  release_notes = excluded.release_notes,
  released_at = excluded.released_at,
  is_latest = excluded.is_latest,
  minimum_android_version = excluded.minimum_android_version,
  status = excluded.status;

revoke all on table public.app_releases from anon, authenticated;
grant select on table public.app_releases to anon, authenticated;
